import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Notification from "@/components/Notification";
import Footer from "@/components/Footer";
import Navabar from "@/components/Navabar";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <CartProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Notification />
          <Navabar />
            {children}
          <Footer />
        </body>
        </CartProvider>
      </UserProvider>
    </html>
  );
}
